[workspace]
members = [ "database",
    "gateway"
]
resolver = "2"

[workspace.package]
authors = ["Tanjiro Project"]
edition = "2021"
include = ["README.md"]
license = "AGPL-3"
repository = "https://github.com/tanjiro-project/tanjiro"
rust-version = "1.80.0"
