[package]
name = "database"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
sqlx = "0.8.2"
